application:
    build: docker/code
    volumes:
        - .:/var/www/bejoe
        - vendor:/var/www/bejoe/vendor

db:
    image: ahmetkizilay/docker-neo4j-auth
    ports:
        - 7474:7474
    cap_add:
        - SYS_RESOURCE
    volumes:
        - data/neo4j/:/var/lib/neo4j/data
    environment:
        - NEO4J_AUTH=neo4j:B3J03

php:
    build: docker/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db

nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - app/logs/nginx/:/var/log/nginx
