parameters:
    neo4j_proxy_dir: '%kernel.cache_dir%/doctrine/neo4j/Proxies'

services:
    # ===== MANAGER =====
    app.manager.base:
        abstract: true
        class: AppBundle\Manager\BaseManager
        calls:
            - [setEntityManager, ["@app.manager.graph"]]

    app.manager.graph:
        class: AppBundle\Manager\GraphManager
        arguments:
            - %neo4j_host%
            - %neo4j_port%
            - %neo4j_proxy_dir%
            - %neo4j_username%
            - %neo4j_password%
            - %kernel.debug%

    app.manager.user:
        class: AppBundle\Manager\UserManager
        parent: app.manager.base
        arguments:
            - @security.encoder_factory
        calls:
            - [setEntityClassName,  ["AppBundle\Entity\User"]]

    # ===== SERVICE =====
    app.service.mailer:
        class: AppBundle\Service\MailerService
        arguments:
            - @mailer
            - @router
            - @templating
            - @translator
            - %mailer%

    # ===== LISTENER =====
    app.listener.email_confirmation:
        class: AppBundle\Listener\EmailConfirmationListener
        arguments:
            - @app.service.mailer
            - @app.manager.user
            - @app.helper.token_generator
        tags:
            - { name: kernel.event_subscriber }

    # ===== SECURITY =====
    security.provider.neo4juser:
        class: AppBundle\Security\Neo4jUserProvider
        arguments: [@app.manager.user]

    security.handler.loggin:
        class: AppBundle\Security\Handler\LoginSuccessHandler
        arguments:
            - @security.http_utils
            - @security.authorization_checker
            - @app.manager.user

    # ===== VALIDATOR =====
    neo4j.ogm.validator.unique:
        class: AppBundle\Validator\UniqueEntityValidator
        arguments: [@app.manager.graph]
        tags:
            - {name: validator.constraint_validator, alias: neo4j.validator.unique}

    # ===== HELPER =====
    app.helper.token_generator:
        class: AppBundle\Helper\TokenGenerator
        arguments: [@logger]
