parameters:
    neo4j_proxy_dir: '%kernel.cache_dir%/doctrine/neo4j/Proxies'

services:
    # ==== MANAGER ==== #
    app.manager.graph:
        class: AppBundle\Manager\GraphManager
        arguments:
            - %neo4j_host%
            - %neo4j_port%
            - %neo4j_proxy_dir%
            - %neo4j_username%
            - %neo4j_password%
            - %kernel.debug%

    app.manager.user:
        class: AppBundle\Manager\UserManager
        arguments:
            - @security.encoder_factory
            - @app.manager.graph
            - AppBundle\Entity\User
#

     # ===== SECURITY ==== #
    security.provider.neo4juser:
        class: AppBundle\Security\Neo4jUserProvider
        arguments: [@app.manager.user]

    security.handler.loggin:
        class: AppBundle\Security\Handler\LoginSuccessHandler
        arguments:
            - @security.http_utils
            - @security.authorization_checker
            - @app.manager.user
